version: "3.9"

services:
    laravel_nginx:
        build:
            context: ./nginx
            dockerfile: nginx.dockerfile
            args: 
                - NGINXGROUP=${NGINXGROUP}
                - NGINXUSER=${NGINXUSER}
        image: laravel_nginx:latest
        container_name: laravel_nginx
        depends_on:
            - laravel_php
            - laravel_mariadb
            - laravel_redis
        ports:
            - 80:80
        volumes:
            - ./src/:/var/www/html/
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    laravel_php:
        build:
            context: ./php
            dockerfile: php.dockerfile
            args:
                - PHPGROUP=${PHPGROUP}
                - PHPUSER=${PHPUSER}
        image: laravel_php:latest
        container_name: laravel_php
        tty: true
        volumes:
            - ./src/:/var/www/html/
        networks:
            - laravel

    laravel_mariadb:
        image: mariadb:latest
        container_name: laravel_mariadb
        restart: always
        environment:
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        volumes:
            - ./my_database/${MARIADB_DATABASE}/:/var/lib/mysql/${MARIADB_DATABASE}/
        networks:
            - laravel

    laravel_redis:
        image: redis:alpine
        container_name: laravel_redis
        restart: always
        networks:
            - laravel

networks:
    laravel:
