version: "3.9"

services:
    laravel_nginx:
        build:
            context: ./nginx
            dockerfile: nginx.dockerfile
            args: 
                - NGINXGROUP=${NGINXGROUP}
                - NGINXUSER=${NGINXUSER}
        image: laravel_nginx:latest
        container_name: laravel_nginx
        depends_on:
            - laravel_php80
            - laravel_mariadb
            - laravel_redis
        restart: always
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    laravel_php80:
        build:
            context: ./php
            dockerfile: php.dockerfile
            args:
                - PHPGROUP=${PHPGROUP}
                - PHPUSER=${PHPUSER}
        image: laravel_php80:latest
        container_name: laravel_php80
        restart: always
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    laravel_mariadb:
        image: mariadb:latest
        container_name: laravel_mariadb
        restart: always
        environment:
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
            - laravel_mariadb:/var/lib/mysql
        networks:
            - laravel

    laravel_redis:
        image: redis:alpine
        container_name: laravel_redis
        restart: always
        networks:
            - laravel

    laravel_composer:
        build:
            context: ./composer
            dockerfile: composer.dockerfile
            args:
                - PHPUSER=${PHPUSER}
                - PHPGROUP=${PHPGROUP}
        image: laravel_composer:latest
        container_name: laravel_composer
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    laravel_nodejs:
        image: node:lts-alpine
        container_name: laravel_nodejs
        working_dir: /var/www/html
        ports:
            - 3000:3000
            - 3001:3001
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

networks:
    laravel:

volumes:
    laravel_mariadb:
