version: "3.9"

services:
    laravel_nginx:
        build:
            context: ./nginx
            dockerfile: nginx.dockerfile
            args: 
                - NGINXGROUP=${NGINXGROUP}
                - NGINXUSER=${NGINXUSER}
        image: laravel_nginx:latest
        container_name: laravel_nginx
        depends_on:
            - laravel_php
            - laravel_mariadb
            - laravel_redis
        tty: true
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    laravel_php:
        build:
            context: ./php
            dockerfile: php.dockerfile
            args:
                - PHPGROUP=${PHPGROUP}
                - PHPUSER=${PHPUSER}
        image: laravel_php:latest
        container_name: laravel_php
        tty: true
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    laravel_mariadb:
        image: mariadb:latest
        container_name: laravel_mariadb
        tty: true
        restart: always
        environment:
            MARIADB_DATABASE: laravel
            MARIADB_USER: user_test
            MARIADB_PASSWORD: password
            MARIADB_ROOT_PASSWORD: password
        volumes:
            - ./db_test:/var/lib/mysql
        networks:
            - laravel

    laravel_redis:
        image: redis:alpine
        container_name: laravel_redis
        tty: true
        restart: always
        networks:
            - laravel

networks:
    laravel:
